### ISSUE TITLE
Kanban board set up

### ISSUE THREAD

**Issue by Kwaku28** [Kwaku28/Space-Travelers-Hub#25]
https://github.com/Kwaku28/Space-Travelers-Hub/projects/1

We are two partners working on this Space Travelers' Hub project

**Comment by Deepakdanger** [comment]
Hi @TEAM, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
